---
apiVersion: "v1"
kind: "Config"
metadata:
  name: "container-structure-test"
spec:
  tests:
    - name: "hadolint"
      image: "<your_image_name>"
      args: ["--no-fail"]
    - name: "hadolint-entrypoint"
      image: "<your_image_name>"
    - name: "hadolint-cmd"
      image: "<your_image_name>"
