DOCKER_RUN = docker run --rm -v $(PWD):/app -w /app golang:1.15.8-buster

lint: ## lint
	$(DOCKER_RUN) markdownlint -f DEPLOY.md README.md || true

build:  ## Build awesome-api
	$(DOCKER_RUN) go build -o awesome-api
	hugo -d dist/

run: ## Run awesome-api application
	./awesome-api >./awesome-api.log 2>&1 &

stop: ## Stop awesome-api application
	pkill awesome-api || true

clean: ## Clean awesome-api application and log
	pkill awesome-api || true
	rm -f awesome-api awesome-api.log coverage-units.out coverage-integrations.out
	rm -rf ./dist

post: ## Create a new blog post
	hugo new posts/$(POST_NAME).md
	sed -i 's/title: .*/title: "$(POST_TITLE)"/' content/posts/$(POST_NAME).md

test: ## Test current connection
	make unit-tests
	make integration-tests

unit-tests: ## Run tests to check for HelloHandler coverage
	$(DOCKER_RUN) go test -v -short -coverprofile=coverage-units.out

integration-tests: ## Run tests to check integrations coverage
	$(DOCKER_RUN) go test -v -coverprofile=coverage-integrations.out

check: ## Check markdown files
	$(DOCKER_RUN) markdownlint ./content/posts/*.md
	$(DOCKER_RUN) markdown-link-check ./content/posts/*.md

validate: ## Validate HTML  W3C Validator
	make build
	git clone https://github.com/holbertonschool/W3C-Validator.git

package: ## Produce awesome-website.zip containing awesome-api and dist directory
	zip -FSr awesome-website.zip . -i dist/ awesome-api
	@if [ ! -f "awesome-website.zip" ]; then \
		echo "Failed to generate awesome-website.zip"; \
		exit 1; \
	fi

.SILENT:
help: ## Display what each command does
	cat Makefile | grep '##' | tr -d '##' | head -n -1
