name: module3_task3

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC every day
  release:
    types:
      - created

jobs:
  build:
    name: Build job
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Execute setup.sh
        run: ./setup.sh
        working-directory: module3_task3
      - name: Validate Makefile execution
        run: |
          make help
          make build
          make lint
          make run
          make unit-tests
          make integration-tests
          make validate
        working-directory: module3_task3
      - name: Package artifact
        run: make package
        working-directory: module3_task3
      - name: Check Release Existence
        id: check_release
        run: |
          if gh release view 1.0.0 &> /dev/null; then
            echo "Release already exists"
            echo "::set-output name=exists::true"
          else
            echo "Release does not exist"
            echo "::set-output name=exists::false"
          fi
      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          draft: true
      - name: Check Release after creating
        run: |
          if gh release view 1.0.0 &> /dev/null; then
            echo "Release already exists"
            echo "::set-output name=exists::true"
          else
            echo "Release does not exist"
            echo "::set-output name=exists::false"
          fi
      - name: Attach Archive
        if: always()
        run: |
          gh release edit 1.0.0 --notes "Release Notes for version 1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
