name: module3_task3

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC every day
  release:
    types:
      - created

jobs:
  build:
    name: Build job
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Execute setup.sh
        run: ./setup.sh
        working-directory: module3_task3
      - name: Validate Makefile execution
        run: |
          make help
          make build
          make lint
          make run
          make unit-tests
          make integration-tests
          make validate
        working-directory: module3_task3
      - name: Package artifact
        run: make package
        working-directory: module3_task3
      - name: archieve ZIP file artifac
        if: ${{github.ref=='refs/heads/main'}}
        uses: actions/upload-artifact@v3
        with:
          name: Saving the zip file
          path: |
            module3_task2/awesome-website.zip
      - name: Create Release
        if: github.ref != 'refs/tags/1.0.0' 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          draft: true
      - name: Attach Archive
        if: always()
        run: |
          gh release upload ${{ github.ref }} module3_task3/awesome-website.zip        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
