---
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run make help
        run: make help
