name: module3_task3

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC every day
  release:
    types:
      - created

jobs:
  build:
    name: Build job
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Execute setup.sh
        run: ./setup.sh
        working-directory: module3_task2
      - name: Validate Makefile execution
        run: |
          make help
          make build
          make lint
          make run
          make unit-tests
          make integration-tests
          make validate
          make stop
          make clean
        working-directory: module3_task2
      - name: Package artifact
        run: make package
        working-directory: module3_task2
      - name: Archive ZIP file artifact
        if: ${{ github.ref == 'refs/tags/*' }}
        run: |
          mkdir -p artifacts
          mv module3_task2/awesome-website.zip artifacts/
        working-directory: ${{ github.workspace }}
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/1.0.0')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/awesome-website.zip
            module3_task3/DEPLOY.md
          body: |
            $(cat module3_task3/DEPLOY.md)
          tag_name: ${{ github.ref }}
      - name: View Release
        run: gh release view 1.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
